### ISSUE TITLE
TemplateLibrary should use Hooks

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#105]
**Is your feature request related to a problem? Please describe.**
For consistency, the `TemplateLibrary` component should be migrated to using [React Hooks](https://reactjs.org/docs/hooks-intro.html).

**Describe the solution you'd like**
Swap from using a `PureComponent` to utilize React Hooks, using other components in this repository as a guide.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nik72619c** [comment]
hi @irmerk , shall I work on this one ?

**Comment by irmerk** [comment]
> hi @irmerk , shall I work on this one ?

Sure thing @nik72619c, this is a great issue.

**Comment by Innovator007** [comment]
Is this issue resolved or can i work on it?

**Comment by irmerk** [comment]
I believe it's all yours @Innovator007

**Comment by Innovator007** [comment]
Hi @irmerk i have added a pull request [here](https://github.com/accordproject/cicero-ui/pull/166), please can you review it :)
