### ISSUE TITLE
Clause Template Hover Effect

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#118]
When the user hovers on a Clause Template, the template name and buttons appear. When the user hovers over a button, it changes color.

@irmerk 

https://projects.invisionapp.com/d/main#/console/16741009/380387451/preview
![image](https://user-images.githubusercontent.com/40569793/63544902-2e569000-c4f4-11e9-8ba4-d0afe32f0bb0.png)

**Comment by irmerk** [comment]
Relates to #89

**Comment by irmerk** [comment]
I believe this issue is finished.
