### ISSUE TITLE
Clause Template Header Tooltip

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#120]
**Is your feature request related to a problem? Please describe.**
IFF the header is truncated, hovering over the text should pop up a tooltip with the full header

**Describe the solution you'd like**
Expound on the hover effect and create a tooltip which will display the full header.

**Describe alternatives you've considered**
Semantic UI React may not be the best route, we may want to create our own component.

**Additional context**
- Related to #118 
- A good start for context is where `Popup` is used from Semantic UI React in the [Markdown Editor](https://github.com/accordproject/markdown-editor/blob/master/src/FormattingToolbar/index.js#L178)
- @Michael-Grover could you provide a mockup of this?

**Comment by johnnyqbui** [comment]
I'd like to take this if thats ok 🙂

**Comment by sanyamdogra** [comment]
Hey @irmerk, I guess this should be closed after the merge of # 151? Thanks.
