### ISSUE TITLE
Update Action Testing

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#123]
Most components require testing for their functionality - typically found in the `actions.js` folders.

A lot of features have been added lately and the tests need to be keeping up.

Refer to #122 for a starting point.

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by 98lenvi** [comment]
I'd like to try this. Please assign it to me

**Comment by irmerk** [comment]
I was thinking more about an integrations test approach, where we mock the activity of a user to make sure changes don't necessarily alter that functionality. So, for instance, if the `ContractEditor` has a clause template in it:
- is the user unable to edit text? 
- Is the user able to edit the variables?
- can the user click on a conditional variable?

**Comment by irmerk** [comment]
Related to #336

**Comment by irmerk** [comment]
Closing for https://github.com/accordproject/web-components/issues/15
