### ISSUE TITLE
ClauseComponent Header Background

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#132]
The linear gradient color behind a `ClauseComponent` header needs to be based off of `clauseProps.CLAUSE_BACKGROUND`

See the declaration of the color [here](https://github.com/accordproject/cicero-ui/blob/master/src/components/styles.js#L26).

**Comment by DianaLease** [comment]
and the trash can background too 🗑 https://github.com/accordproject/cicero-ui/blob/4d2c4763b2641a047dc2cb6d49fc670b0f5e5e9f/src/components/styles.js#L48
