### ISSUE TITLE
Cursor Disappear at the Top of Clause Component

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#139]
**Describe the bug**
When navigating with a keyboard through the `ContractEditor`, the cursor disappears and cannot be gained back without alt-tabbing or using the mouse

**To Reproduce**
1. Go to [Template Studio v2](https://accordproject-studio.netlify.com/)
2. Create multiple lines or paragraphs
3. Add a clause template in the middle of these lines
4. Navigate from below the clause template up into it using the keyboard
4. Now navigate from in the clause template up out of it using the keyboard
4. Now navigate from above the clause template down into it using the keyboard

**Expected behavior**
Navigating through the top of a clause template should not cause the cursor to disappear

**Screenshots**
[A Loom recording of the bug is here](https://www.loom.com/share/b85228c8e0f641419476b8e8c0d5165b).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
This may have something to do with how we implement the clause template header (the one that appears when you hover over the clause template with a mouse)

**Comment by christyjacob4** [comment]
Hey @irmerk  I'd like to take up this issue :)

**Comment by Lawrence4code** [comment]
If this is still open, I'd like to work on it, thanks.

**Comment by irmerk** [comment]
@christyjacob4 and @Lawrence4code, any update on this? Opening it up in the meantime.
