### ISSUE TITLE
Utilize Cicero v0.20

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#143]
**Is your feature request related to a problem? Please describe.**
Once `alpha1` is out for Cicero, update the UI to use the markdown transform stack

**Describe the solution you'd like**
N/A

**Additional context**
- N/A

**Comment by jeromesimeon** [comment]
We're at `0.20.0-beta.2` now ;) Maybe this issue should be renamed to simply `0.20` ?

**Comment by irmerk** [comment]
Closed with [this release](https://github.com/accordproject/cicero-ui/releases/tag/v0.2.0)
