### ISSUE TITLE
ClausePlugin README

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#145]
# ClausePlugin

This should have developer documentation associated with it to showcase how it can be used and its purpose.

> ClausePlugin: A custom Slate plugin for embedding a clause node within a document

**Comment by Niladri24dutta** [comment]
@irmerk Can I work on this ? Where should it be added in documentation?

**Comment by irmerk** [comment]
I think this could be in `https://github.com/accordproject/cicero-ui/tree/master/src/plugins` unless there is a better idea at the moment.

**Comment by Niladri24dutta** [comment]
> 
> 
> I think this could be in `https://github.com/accordproject/cicero-ui/tree/master/src/plugins` unless there is a better idea at the moment.

Thanks I will do it accordingly

**Comment by irmerk** [comment]
Opening this back up after 14 days stale.

**Comment by raghav4** [comment]
@irmerk , I'm working on this!
