### ISSUE TITLE
Search bar styling

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#183]
Change the search bar styling to match [this mockup](https://invis.io/9GRP1QB8D2U#/370418068_contract_-_Clause_Edit_Within_Contract_Editor_Dark). Click "inspect" in the lower right corner to view the CSS. You may need to request access. You can ignore everything about the mockup except the search bar.

![image](https://user-images.githubusercontent.com/40569793/67427597-62a90400-f5aa-11e9-92b1-67bdd8c78ff0.png)

Additionally, if you zoom in on the search bar as it currently stands, there appears to be an extra border around it. Remove this extra border. 
![image](https://user-images.githubusercontent.com/40569793/67427676-8c622b00-f5aa-11e9-8a66-97ad821e5ea6.png)

**Comment by ENeska** [comment]
Can I work with this issue? ;)

**Comment by Michael-Grover** [comment]
@ENeska yes, thank you. Let me know if you need any more details

**Comment by ENeska** [comment]
@Michael-Grover I have a question. Did I build the project well? Because my console is "red" :(

![image](https://user-images.githubusercontent.com/24510802/67433961-6dcf5480-f5e9-11e9-864a-a01a617a8d72.png)

**Comment by Michael-Grover** [comment]
@irmerk @DianaLease or @jeromesimeon may be able to help with code related questions

**Comment by irmerk** [comment]
@ENeska those are quite recent warnings from `React` that don't quite matter at the moment, so you can disregard them.

**Comment by abnazhor** [comment]
Hello, can I work on this?

**Comment by Michael-Grover** [comment]
Hi @abnazhor , it looks like @ENeska is no longer working on this, so sure go for it. Thank you

**Comment by Innovator007** [comment]
Is this thing done or can i work on it?

**Comment by abnazhor** [comment]
@Innovator007 Working on it!
