### ISSUE TITLE
Button styling

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#184]
Change the button styling to match [this mockup](https://invis.io/9GRP1QB8D2U#/370418068_contract_-_Clause_Edit_Within_Contract_Editor_Dark). Click "inspect" in the lower right corner to view the CSS. You may need to request access. You can ignore everything about the mockup except the button styling

![image](https://user-images.githubusercontent.com/40569793/67427884-02ff2880-f5ab-11e9-983a-cb94be3bdab8.png)

On hover, the button background color should turn white. The text should remain the same color.

**Comment by abnazhor** [comment]
I would love to work on this, can I?

**Comment by Michael-Grover** [comment]
@abnazhor yes, thank you. Let me know if you need any more details

**Comment by Michael-Grover** [comment]
Thanks again @abnazhor
