### ISSUE TITLE
ErrorLogger Displays Only 4-5 Errors

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#187]
**Describe the bug**
The `ErrorLogger` component only displays 4-5 errors max

**To Reproduce**
1. Open the [Netlify demo of TSv2](https://accordproject-studio.netlify.com)
2. Add 6-8 clauses
3. Type a letter at the beginning of each one to cause a parse error
4. Open the `ErrorLogger` at the bottom
5. Notice only 4 or 5 are displayed

**Expected behavior**
This component should display 4 errors at a time, with a scroll bar if more than 4 exist

**Additional context**
Current behavior, notice how many errors are expanded vs. how many the component says it has:
<img width="1676" alt="Screen Shot 2019-10-24 at 11 39 23 AM" src="https://user-images.githubusercontent.com/36460856/67501929-19f95580-f653-11e9-8937-627a983c63f8.png">

**Comment by anusha5695** [comment]
Hi I would like to work on this

**Comment by anusha5695** [comment]
Hi @irmerk : I have pushed the changes.
