### ISSUE TITLE
Contract Editor Scrollbar is Obtrusive

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#188]
**To Reproduce**
1. Run locally with `cicero-ui` linked through `npm link`
2. Add enough line breaks to show the scroll bar, add twice as many more
3. Scroll to the bottom and notice the scrollbar background cutting into the toolbar

**Expected behavior**
The scrollbar should either have no background or begin below the toolbar

**Screenshots**
![Screen Shot 2019-10-17 at 2 27 26 PM](https://user-images.githubusercontent.com/36460856/67039170-cfc22280-f0ee-11e9-9ffe-bc978a9f1972.png)

**Additional context**
Linked to [TSv2 Issue 114](https://github.com/accordproject/template-studio-v2/issues/114)

**Comment by irmerk** [comment]
@V1shvesh is working on this currently.

**Comment by ravijyoti310** [comment]
can I also work on it??

**Comment by irmerk** [comment]
@v1shvesh your call, could you use help?

**Comment by V1shvesh** [comment]
I don't think it's a complex enough issue to require two devs working on this. But nevertheless,  I'll share my progress by tomorrow. We'll find out if we could indeed use any more hands on this.

**Comment by V1shvesh** [comment]
Working on this rn, I'll post an progress update soon.

**Comment by V1shvesh** [comment]
So, the actual issue is in `@accordproject/markdown-editor`. I went inside and tried fixing the issue by giving the component `EditorWrapper` a fixed height and `overflow-y: scroll`.

It is unfortunate for this to be happening again, but I guess we should post this issue there. 

@irmerk I've updated the code and will submit a PR there soon.

**Comment by irmerk** [comment]
@V1shvesh yeah I think that would be best. Essentially copy paste this issue, but then link this issue as a related issue so there is context of where it originated from.

**Comment by shrey-sachdeva2000** [comment]
Hi @irmerk, I'd like to work on this if this is still unresolved. Although, I'm not sure how I can view changes to the UI as this issue seems to originate from `markdown-editor` as previously mentioned.

**Comment by elit-altum** [comment]
Hey @irmerk I have made some progress on this. Can you help me with further details, like animations, icons etc. ?
Sorry @shrey-sachdeva2000 I didn't know you were working on it. I followed the issue trail from https://github.com/accordproject/markdown-editor/issues/175

![Added-Animation](https://user-images.githubusercontent.com/41413622/75583421-8e298700-5a93-11ea-84cf-d9d33c4316d1.gif)

**Comment by shrey-sachdeva2000** [comment]
> Hey @irmerk I have made some progress on this. Can you help me with further details, like animations, icons etc. ?
> Sorry @shrey-sachdeva2000 I didn't know you were working on it. I followed the issue trail from [accordproject/markdown-editor#175](https://github.com/accordproject/markdown-editor/issues/175)
> 
> ![Added-Animation](https://user-images.githubusercontent.com/41413622/75583421-8e298700-5a93-11ea-84cf-d9d33c4316d1.gif)

No problem @elit-altum, please go ahead!

**Comment by irmerk** [comment]
@shrey-sachdeva2000 and @elit-altum I believe this issue is resolved. If you can produce a similar issue or the same one without being in `template-studio-v2`, then open another issue.

**Comment by elit-altum** [comment]
> 
> 
> @shrey-sachdeva2000 and @elit-altum I believe this issue is resolved. If you can produce a similar issue or the same one without being in `template-studio-v2`, then open another issue.

@irmerk This issue was closed on it's trail because it went stale. I think this functionality is not yet present.

**Comment by irmerk** [comment]
I don't think there is an issue with the scrollbar anymore. @DianaLease you fixed that, correct?
