### ISSUE TITLE
Block quote toolbar works in lock text mode

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#209]
**Describe the bug**
Can use the block quote toolbar button, when the editor is in lockText mode.

**To Reproduce**
1. npm run dev
2. http://localhost:8080
3. Set the cursor inside the clause
3. Press the block quote toolbar button
4. See that the clause text is modified

**Expected behavior**
When in lock text mode the clauses should not be modifiable.

**Comment by irmerk** [comment]
Relates to [`markdown-editor` Issue #122](https://github.com/accordproject/markdown-editor/issues/122)
