### ISSUE TITLE
Link toolbar button works in lock text mode

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#211]
**Describe the bug**

Can use the link toolbar button, when the editor is in lockText mode.

To Reproduce

1. npm run dev
1. http://localhost:8080
1. Set the cursor inside the clause
1. Press the link toolbar button
1. See that the clause text is modified

**Expected behavior**

When in lock text mode the clauses should not be modifiable.

**Comment by irmerk** [comment]
Relates to [`markdown-editor` Issue #122](https://github.com/accordproject/markdown-editor/issues/122)
