### ISSUE TITLE
Lists are not being rendered correctly

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#213]
**Describe the bug**
Ordered and unordered lists are not being rendered correctly.

**To Reproduce**
1. type the text: one, two, three (on separate lines)
2. select the text
3. press the ordered list button
4. the formatting changes but no number prefix is displayed
5. note same behaviour for bulleted lists

**Expected behavior**
Lists should be rendered correctly.

**Comment by irmerk** [comment]
Relates to [`markdown-editor` PR #174](https://github.com/accordproject/markdown-editor/pulls/174)
