### ISSUE TITLE
Variable Modal

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#225]
**Is your feature request related to a problem? Please describe.**
Clicking on a variable should open a type-specific editor (such as a calendar editor for a DataTime variable)

This is separate from the issue of creating a variable when editing or creating a template.

We need type specific editors for the following variables:

- date & time (optional timezone offset)
- address
- monetary amount
- boolean ? (@jeromesimeon)
- string
- number
  - floating point
  - whole
- enumerations
- accordParty

Potential libraries:
- [Wojtekmaj](http://projects.wojtekmaj.pl/react-calendar/)
- [AirBnB](https://github.com/airbnb/react-dates)

See this invision:
https://projects.invisionapp.com/d/main#/console/16741009/394829377/preview

![image](https://user-images.githubusercontent.com/40569793/69447762-33122680-0d25-11ea-9126-2aa424ae98c5.png)

**Comment by Michael-Grover** [comment]
@irmerk do you know of any frameworks/plugins/whatever you'd call them for type specific form fields like address, calendar, time, etc?

**Comment by Michael-Grover** [comment]
Before a user chooses a variable type
https://projects.invisionapp.com/d/main#/console/16741009/388109653/preview

After a user chooses a variable type
https://projects.invisionapp.com/d/main#/console/16741009/388109652/preview

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/69447762-33122680-0d25-11ea-9126-2aa424ae98c5.png)

**Comment by irmerk** [comment]
There could be consideration for tabbing between variables, and on focus maybe the popup appears?
