### ISSUE TITLE
Error Logger should handle errors in various formats

### ISSUE THREAD

**Issue by DianaLease** [accordproject/cicero-ui#226]
**Describe the bug**
The Error Logger component causes the app to crash when it receives an error in an unexpected format (ie. `Error: Parsing clause text returned a null AST. This may mean the text is valid, but not complete.`) The Error Logger should be resilient and adapt to display this type of error.

**Comment by jeromesimeon** [comment]
There should probably be a catch all for exceptions?

**Comment by dselman** [comment]
I've modified `cicero-core` to use a `ParseException` for all code branches:
https://github.com/accordproject/cicero/commit/1020d127ef9ef20d010a3f040de5a8c405a47f6e

Once this change is released it should resolve this issue.
