### ISSUE TITLE
Bulleted list variables

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#230]
For lists with variables, allow a user to hover over the clause template to see add and delete buttons. click an add button to add another instance of the list item, with the new list item's variables set to the previous list item's variables by default. Click the minus button to remove that list item.

https://ancient-voice-6638.animaapp.io
![image](https://user-images.githubusercontent.com/40569793/69374546-46b18480-0c74-11ea-9e14-fb64726715cf.png)

**Comment by jeromesimeon** [comment]
Only part of the text inside a list would be editable. How would we make the distinction?

Example from the volume discount with a list:

<img width="705" alt="Screenshot 2019-11-21 at 2 50 06 PM" src="https://user-images.githubusercontent.com/670099/69371792-8aa18b00-0c6e-11ea-877f-db500e41cfed.png">

**Comment by Michael-Grover** [comment]
@jeromesimeon I addressed your comment in the edited description for this issue

**Comment by Michael-Grover** [comment]
[icons.zip](https://github.com/accordproject/cicero-ui/files/3876963/icons.zip)

Here are the icons for the issue

**Comment by DianaLease** [comment]
What happens if a user removes all list items and then tries to add a list item? Should a user be allowed to remove all list items?

**Comment by jerrybuks** [comment]
Does this Issuse, still need someone to work on it ?

**Comment by irmerk** [comment]
@jerrybuks it does. If you're interested, I would review the work done in #233, it will likely be similar to the work needed for this issue.

**Comment by Michael-Grover** [comment]
> What happens if a user removes all list items and then tries to add a list item? Should a user be allowed to remove all list items?

Let's say that when there is only one list item, the user can not remove that item. They can only edit that item or add another item.

**Comment by jerrybuks** [comment]
> @jerrybuks it does. If you're interested, I would review the work done in #233, it will likely be similar to the work needed for this issue.

okay, yeah, I'm interested.

**Comment by jerrybuks** [comment]
could someone please point me to any AP template, where bulleted lists are being used, so as to enable me to do some inspection and know what components am supposed to be working on

**Comment by irmerk** [comment]
Yes! https://templates.accordproject.org/volumediscountulist@0.2.1.html

**Comment by jerrybuks** [comment]
@irmerk, I'm trying to find a template,  where the issue in #233, which led to #288 is being used, but I can't find any, could you please point me to any template where "conditional variables" is being used

**Comment by irmerk** [comment]
OH Conditional variables are used in https://templates.accordproject.org/latedeliveryandpenalty@0.15.1.html

**Comment by jerrybuks** [comment]
okay, thank you. I observed this only when running cicero-ui locally, but when running template studio both locally and even on the Accord site, the conditional variable feature seems not to be available/working, is this intentional?

**Comment by jeromesimeon** [comment]
> okay, thank you. I observed this only when running cicero-ui locally, but when running template studio both locally and even on the Accord site, the conditional variable feature seems not to be available/working, is this intentional?

@jerrybuks Not sure if template studio v2 has been updated to the latest Cicero UI?

**Comment by jerrybuks** [comment]
> > okay, thank you. I observed this only when running cicero-ui locally, but when running template studio both locally and even on the Accord site, the conditional variable feature seems not to be available/working, is this intentional?
> 
> @jerrybuks Not sure if template studio v2 has been updated to the latest Cicero UI?

ooh!, okay, I get...

**Comment by jerrybuks** [comment]
Hello, please I'm currently stuck with this issue, it seems the ciceroMarkTransformer(which this project relies on), does not support list variables yet. please if it does, I'm trying to create a bulleted list variable in the demo file, before moving on to add the addition and deletion functionality, but it can find a syntax to use for this,  I observed that for creating variables, a "variable" tag was used which the ciceroMark transformer then works on, for conditional the "if" tag was used, but for created bulleted list, they seem to be no syntax which can be understood by the ciceroMark transformer for doing this, please help?

**Comment by jerrybuks** [comment]
> Hello, please I'm currently stuck with this issue, it seems the ciceroMarkTransformer(which this project relies on), does not support list variables yet. please if it does, I'm trying to create a bulleted list variable in the demo file, before moving on to add the addition and deletion functionality, but it can find a syntax to use for this, I observed that for creating variables, a "variable" tag was used which the ciceroMark transformer then works on, for conditional the "if" tag was used, but for created bulleted list, they seem to be no syntax which can be understood by the ciceroMark transformer for doing this, please help?

@jeromesimeon could you please, give me any hint on this

**Comment by jeromesimeon** [comment]
> > Hello, please I'm currently stuck with this issue, it seems the ciceroMarkTransformer(which this project relies on), does not support list variables yet. please if it does, I'm trying to create a bulleted list variable in the demo file, before moving on to add the addition and deletion functionality, but it can find a syntax to use for this, I observed that for creating variables, a "variable" tag was used which the ciceroMark transformer then works on, for conditional the "if" tag was used, but for created bulleted list, they seem to be no syntax which can be understood by the ciceroMark transformer for doing this, please help?
> 
> @jeromesimeon could you please, give me any hint on this

There is some support in `markdow-cicero`, but this may need some suggestion from the UI side to know if the translation to Slate is appropriate or needs some adjustment.

You should be able to start with the following tests samples:
`test/data/clauseulist.md`
`test/data/ulist.md`
`test/data/ulist-nolist.md`

For instance `ulist.md`:
```
#### Discount.

The Discount is determined according to the following table:
 ```<list/>
- 0.0$ million <= Volume < 1.0$ million : 3.1%
- 1.0$ million <= Volume < 10.0$ million : 3.1%
- 10.0$ million <= Volume < 50.0$ million : 2.9%
- 50.0$ million <= Volume < 500.0$ million : 2.5%
- 500.0$ million <= Volume < 1000.0$ million : 1.2%
- 1000.0$ million <= Volume < 1000000.0$ million : 0.1%
 ```
```

Which you can use e.g., to replace the current example in Cicero UI.

The `clauseulist` one may be a good one too (but you will have to check the URL for that clause to make sure it is correct).

If you transform it to Slate, you can see a variable containing list nodes:
```
bash-3.2$ markus parse --sample /Users/jeromesimeon/git/markdown-transform/packages/markdown-cicero/test/data/ulist.md  --slate
3:35:38 PM - info:
{
  "object": "value",
  "document": {
    "object": "document",
    "nodes": [
      {
        "object": "block",
        "data": {
        },
        "type": "heading_four",
        "nodes": [
          {
            "object": "text",
            "text": "Discount.",
            "marks": []
          }
        ]
      }, 
      {
        "object": "block",
        "type": "paragraph",
        "nodes": [
          {
            "object": "text",
            "text": "The Discount is determined according to the following table:",
            "marks": []
          }
        ],
        "data": {
        }
      }, 
      {
        "object": "block",
        "data": {
          "tight": "true",
          "kind": "variable"
        },
        "type": "ul_list",
        "nodes": [
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "0.0$ million <= Volume < 1.0$ million : 3.1%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }, 
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "1.0$ million <= Volume < 10.0$ million : 3.1%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }, 
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "10.0$ million <= Volume < 50.0$ million : 2.9%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }, 
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "50.0$ million <= Volume < 500.0$ million : 2.5%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }, 
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "500.0$ million <= Volume < 1000.0$ million : 1.2%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }, 
          {
            "object": "block",
            "type": "list_item",
            "data": {
            },
            "nodes": [
              {
                "object": "block",
                "type": "paragraph",
                "nodes": [
                  {
                    "object": "text",
                    "text": "1000.0$ million <= Volume < 1000000.0$ million : 0.1%",
                    "marks": []
                  }
                ],
                "data": {
                }
              }
            ]
          }
        ]
      }
    ],
    "data": {
    }
  }
}
```
