### ISSUE TITLE
Conditional variables UI

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#233]
**Is your feature request related to a problem? Please describe.**
As a user I would like to enable and disable conditional variables, and to switch between two options in conditional variables.

**Describe the solution you'd like**
See this Loom video explaining the UI:
https://www.loom.com/share/694e7927a744475a98b1cf81154c3673

Smart Clause with three conditional variables, marked with red text
https://projects.invisionapp.com/d/main#/console/16741009/394631841/preview
![image](https://user-images.githubusercontent.com/40569793/69457270-b1c58e80-0d3a-11ea-890b-a4a5f99c9d5c.png)

User hovers over Smart Clause to see there is an additional conditional variable that can be enabled. Signified by a plus icon.
https://projects.invisionapp.com/d/main#/console/16741009/394631840/preview
![image](https://user-images.githubusercontent.com/40569793/69457262-aa9e8080-0d3a-11ea-89d7-a19d9e0d5758.png)

User hovers over icon to see what text will appear when they click on it.
https://projects.invisionapp.com/d/main#/console/16741009/394631839/preview
![image](https://user-images.githubusercontent.com/40569793/69457239-9eb2be80-0d3a-11ea-8657-ba0de930107c.png)

The user clicked on the text, making the conditional variable text appear.
https://projects.invisionapp.com/d/main#/console/16741009/394631838/preview
![image](https://user-images.githubusercontent.com/40569793/69457128-5d221380-0d3a-11ea-9825-b7dbd4218f08.png)

The user is hovering over conditional variable text. A tooltip tells the user the text will be hidden if they click
https://projects.invisionapp.com/d/main#/console/16741009/394631837/preview
![image](https://user-images.githubusercontent.com/40569793/69457156-6f9c4d00-0d3a-11ea-8577-2ab84a26b9c0.png)

The user has clicked to hide the text and it is hidden again
https://projects.invisionapp.com/d/main#/console/16741009/394631840/preview
![image](https://user-images.githubusercontent.com/40569793/69457187-82af1d00-0d3a-11ea-9961-0a2f180e52de.png)

If the user hovers on a conditional variable that switches between two text options, they will see a message like this. When they click, the text will change to the other option.
https://projects.invisionapp.com/d/main#/console/16741009/394633329/preview
![image](https://user-images.githubusercontent.com/40569793/69457528-3c0df280-0d3b-11ea-9d58-70eaf6cbbff2.png)

**Comment by jeromesimeon** [comment]
Currently, there is not enough information in the SlateDOM to know what the alternative text of a variable is. One possibility to address that is to change the MD representation for conditional variables to always have the alternative text.

Proposed format is as follows:
```
Late Delivery and Penalty.
----

In case of delayed delivery<if id="forceMajeure" whenTrue=" except for Force Majeure cases," whenFalse=" even when there is a Force Majeure," value="true"/>
<variable id="seller" value="%22Dan%22"/> (the Seller) shall pay to <variable id="buyer" value="%22Steve%22"/> (the Buyer) for every <variable id="penaltyDuration" value="2%20days"/>
of delay penalty amounting to <variable id="penaltyPercentage" value="10.5"/>% of the total value of the Equipment
whose delivery has been delayed. Any fractional part of a <variable id="fractionalPart" value="days"/> is to be
considered a full <variable id="fractionalPart" value="days"/>. The total amount of penalty shall not however,
exceed <variable id="capPercentage" value="55.0"/>% of the total value of the Equipment involved in late delivery.
If the delay is more than <variable id="termination" value="15%20days"/>, the Buyer is entitled to terminate this Contract.
```

**Comment by irmerk** [comment]
Reopening for this/that conditionals
