### ISSUE TITLE
Raise Error for Unsupported Templates

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#237]
**Is your feature request related to a problem? Please describe.**
We need a short term solution to notify users that certain Cicero v0.20 features are not supported in the UI:
- variable lists
- nested lists
- conditionals
- code blocks

**Describe the solution you'd like**
Add a query `isSupported` to the `ClausePlugin`

**Additional context**
We don’t want Cicero to know about the limitations of the editor - it would create a conceptual cyclic dependency. These dynamic lists should be represented in the DOMs so the editor can handle them appropriately.

This work will coincide with [`markdown-transform` #130](https://github.com/accordproject/markdown-transform/issues/130)

[For reference][slate], `findClauseNode` is an example of an existing custom query we have

[slate]: https://docs.slatejs.org/guides/commands-and-queries

**Comment by jeromesimeon** [comment]
PR #239 has some initial support for detecting / rejecting Slate DOMs with unsupported features.

The list of features deemed unsupported is a little longer than that indicated in the issue:
   - conditional variables
   - computed variables
   - list variables
   - code blocks
   - html blocks or inlines
   - images
   - nested lists

Let me know if this is wrong.

**Comment by jeromesimeon** [comment]
@irmerk @DianaLease Can we consider this issue closed with #242 ?
