### ISSUE TITLE
Allow user to specify search font color

### ISSUE THREAD

**Issue by DianaLease** [accordproject/cicero-ui#241]
**Describe the bug**
The new white color for search field does not look good when application using the template library is using a light background

**Screenshots**
![Screen Shot 2019-12-06 at 11 50 18 AM](https://user-images.githubusercontent.com/20543103/70340431-c87de200-181e-11ea-9c72-816d4b1d78e3.png)

**Comment by elit-altum** [comment]
@DianaLease I think this issue is resolved. Can this be closed?

**Comment by irmerk** [comment]
Yes I believe so
