### ISSUE TITLE
PASTE: Trying to Paste a Clause raises errors, does nothing

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero-ui#251]
When trying to copy/paste a clause within the UI raises some error:

```
react-dom.development.js:475 Uncaught TypeError: editor.props.clausePluginProps.pasteToContract is not a function
    at eval (ClausePlugin.js:181)
    at Block.withMutations (immutable.es.js:2284)
    at eval (ClausePlugin.js:174)
    at eval (immutable.es.js:3241)
    at List.withMutations (immutable.es.js:2284)
    at List.map (immutable.es.js:3239)
    at onPaste (ClausePlugin.js:172)
    at next (slate.es.js:11382)
    at onPaste (slate-react.es.js:5216)
    at next (slate.es.js:11382)
```

**Comment by irmerk** [comment]
The [demo][demo] for this repo has no `pasteToContract` in it currently, which is likely causing the issue. The function is required in the [README][readme].

[demo]: https://github.com/accordproject/cicero-ui/blob/master/demo/src/index.js
[readme]: https://github.com/accordproject/cicero-ui/blob/master/src/plugins/README.md

**Comment by nik72619c** [comment]
@irmerk what can be the possible resolution for this? I needed some more context on it.

**Comment by irmerk** [comment]
@nik72619c I suspect this will eventually be solved by our aim to have a more robust demo via Storybook, the issue tracking that is [here](https://github.com/accordproject/cicero-ui/issues/315). Still unsure how that will pan out, but I imagine one of the examples having a `pasteToContract` which handles replicating the clause template object in slate?
