### ISSUE TITLE
Edit and Testing Buttons

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#273]
**Is your feature request related to a problem? Please describe.**
Clause Components should have icons in addition to delete in order to edit and test.

**Describe the solution you'd like**
Add icons with customizable functionality.

**Additional context**
@Michael-Grover please provide AP colors

**Comment by Michael-Grover** [comment]
the same colors as the trash icon 
![image](https://user-images.githubusercontent.com/40569793/73849783-82320880-47f8-11ea-887e-d0cbc6b281ab.png)
