### ISSUE TITLE
Restyle navigation sizing

### ISSUE THREAD

**Issue by DianaLease** [accordproject/cicero-ui#276]
**Is your feature request related to a problem? Please describe.**
Headings in navigation can appear to be truncated prematurely, especially on larger screens

**Describe the solution you'd like**
Either:
1. Make width of the navigation component adjust based on screen size and use CSS to determine when to truncate & add the ellipsis [text-overflow - CSS: Cascading Style Sheets \| MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)
-- or -- 
2. Make the navigation component resizable (allowing the user to drag to make it narrower or wider) and use CSS to determine when to truncate & add the ellipsis

**Comment by Michael-Grover** [comment]
I think solution two relates to expandable and collapsible sidebars. the following linked issue gives the sidebars boundaries that can be dragged.

https://github.com/accordproject/template-studio-v2/issues/80

**Comment by jerrybuks** [comment]
can I work on this?

**Comment by DianaLease** [comment]
> can I work on this?

Sure, go ahead! I'll assign it to you.

**Comment by jerrybuks** [comment]
okay, on it

**Comment by jerrybuks** [comment]
> > can I work on this?
> 
> Sure, go ahead! I'll assign it to you.

I've created a pull request for this feature, please review. [https://github.com/accordproject/cicero-ui/pull/313](url)
