### ISSUE TITLE
Missing entries in .gitignore

### ISSUE THREAD

**Issue by adrijshikhar** [accordproject/cicero-ui#289]
**Describe the bug**
.vsocde and .dist are two folders that are created by Visual Studio Code.
.vscode contains the local settings for that workspace.
.dist is created by C++ extension in vscode.
These are local changes made and hence should be present in .gitignore so that no one accidentally commits these files.

**To Reproduce**
1. Open a terminal and go to the root of the repo
2. Type `code .` and let vsocde open
3. Go back to the terminal and type `ls` 
4. See the error, two new folders will be created if you use custom settings and C++ extension

**Expected behavior**
.vscode and .dist should be present in .gitignore

**Screenshots**
![Screenshot_20200221_222352](https://user-images.githubusercontent.com/41939219/75054621-71240f80-54f9-11ea-9b1a-24a1317f5f2e.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Browser: Chrome
 - Version 80 (Official Build) (64-bit)

**Comment by irmerk** [comment]
I'm not sure I understand the purpose of this, I don't think the repository has an issue with a `.vscode` or `.dist` folder.

**Comment by adrijshikhar** [comment]
`.vscode` contains a file named `settings.json`, which contains the local settings for the vscode in that particular workspace. So if anyone accidentally commits this, and some other guy pulls his changes and his vscode will create its own `settings.json` which will increase the number of line changes and might break some of the custom changes that this user has applied to his vscode.
