### ISSUE TITLE
Update React LifeCycle Methods

### ISSUE THREAD

**Issue by elit-altum** [accordproject/cicero-ui#293]
**Describe the bug**
The life cycle methods ```componentWillMount``` and ```componentWillReceiveProps ``` have been deprecated and are declared unsafe for use (React v16.3) . These should be renamed to the new lifecycle methods.

**To Reproduce**
1. On opening the app a browser warning will be found in the console for the same

**Expected behavior**
The lifecycle methods should be updated for security and future-proofing the codebase.

**Screenshots**
![image](https://user-images.githubusercontent.com/41413622/75096994-89fcf580-55cb-11ea-99f7-f4b36124b2d7.png)

**Additional context**
I would like to work on resolving this issue using and ```componentDidMount``` and ```getDerivedStateFromProps``` lifecycle methods respectively.
*Alternate*
I can also use the ```UNSAFE_``` prefix before these lifecycle methods which will continue their functionality as it is and just stop the warnings in the browser. (Not recommended)

**Comment by elit-altum** [comment]
@irmerk Please review and suggest!

**Comment by irmerk** [comment]
Where are these being used? I would imagine updating the component to React Hooks would be a better solution.

**Comment by elit-altum** [comment]
@irmerk I can't pinpoint them exactly. Maybe they are from the semantic UI. But will it be fine if I refactor the Welcome component to a functional component, as it does use componentDidMount and instead the useEffect hook would be able to handle that better using dependencies ?
It would also help in cleaning up the code significantly.

**Comment by elit-altum** [comment]
@irmerk One more thing, while trying to refactor the components I also found the fix to https://github.com/accordproject/template-studio-v2/issues/135 . Do you still want the change of colors? (as this issue was closed)

![image](https://user-images.githubusercontent.com/41413622/75468249-ea68aa00-59b2-11ea-9eaf-c96dd43c156d.png)
