### ISSUE TITLE
Misspell across the repo

### ISSUE THREAD

**Issue by adrijshikhar** [accordproject/cicero-ui#294]
There are spelling mistakes across the repo.

**Comment by irmerk** [comment]
You'll want to make the change to the README in all the other repos as wel:

```
cicero
ergo
concerto
markdown-transform
markdown-editor
cicero-template-library
models
techdocs
cicero-vscode-extension
cicero-ui
concerto-ui
template-studio-v2
```

**Comment by adrijshikhar** [comment]
Ok i will.
PS: `cicero-vscode-extension` does not have any spelling mistake errors.
