### ISSUE TITLE
npm link "@accordproject/cicero-ui" fails with permission issues

### ISSUE THREAD

**Issue by jerrybuks** [accordproject/cicero-ui#299]
I'm trying to setup this repo, so as to contribute but  when I run "npm link @accordproject/cicero-ui", I get this error
![Screenshot from 2020-02-25 15-42-50](https://user-images.githubusercontent.com/39066907/75258070-3d413680-57e6-11ea-8df0-a1f1a8327182.png)

**Comment by jeromesimeon** [comment]
@jerrybuks Why do you want to link? What are you trying to do?

Looking at the trace it seems to be looking in `/usr/local/lib` is that where your `@accordproject/cicero-ui` package is? Did you check the permissions in that folder?

**Comment by jerrybuks** [comment]
The development guide mentions doing the linking as part of the steps for setting up the repo for development. I did try ignoring this step and just running "npm start" but the site spun up doesn't seem to be the  complete UI, but seems to contain only the editor, as I can't find the navigation bar
![Screenshot from 2020-02-25 15-58-21](https://user-images.githubusercontent.com/39066907/75259509-7084c500-57e8-11ea-95d8-6c68343b1b80.png)

**Comment by jeromesimeon** [comment]
> The development guide mentions doing the linking as part of the steps for setting up the repo for development. I did try ignoring this step and just running "npm start" but the site spun up doesn't seem to be the complete UI, but seems to contain only the editor, as I can't find the navigation bar
> ![Screenshot from 2020-02-25 15-58-21](https://user-images.githubusercontent.com/39066907/75259509-7084c500-57e8-11ea-95d8-6c68343b1b80.png)

Cicero UI are React components not a full UI. You can use them to create your own UI if you want. That demo looks right!

**Comment by jeromesimeon** [comment]
@irmerk Are the developers instructions up to date?

**Comment by jerrybuks** [comment]
ooh, okay, I wanted to contribute to an issue opened by Diana concerning "Restyling the navigation size", please how do I get to preview changes I make to Cicero Ui components, like the Navigation component? should I just import the components in the file being displayed in the demo, so I can preview then remove the import when I'm done?

**Comment by jeromesimeon** [comment]
> ooh, okay, I wanted to contribute to an issue opened by Diana concerning "Restyling the navigation size", please how do I get to preview changes I make to Cicero Ui components, like the Navigation component? should I just import the components in the file being displayed in the demo, so I can preview then remove the import when I'm done?

That's a really good question. I think we've been using https://github.com/accordproject/template-studio-v2 to test those components in context. Maybe @irmerk or @DianaLease can confirm?

**Comment by DianaLease** [comment]
> > ooh, okay, I wanted to contribute to an issue opened by Diana concerning "Restyling the navigation size", please how do I get to preview changes I make to Cicero Ui components, like the Navigation component? should I just import the components in the file being displayed in the demo, so I can preview then remove the import when I'm done?
> 
> That's a really good question. I think we've been using https://github.com/accordproject/template-studio-v2 to test those components in context. Maybe @irmerk or @DianaLease can confirm?

That is what we were doing. I think it would be good to get them in the cicero-ui demo though to test easily there. That would be a good thing to add and keep (as opposed to removing when you are done @jerrybuks)

**Comment by irmerk** [comment]
Yes we are using `template-studio-v2` heavily as a development environment for `cicero-ui`. You should have two terminals open, one to your `cicero-ui` and one to `template-studio-v2`

In `cicero-ui` run:
1. `npm install`
2. `npm run build`
3. `npm run transpile`
4. `npm link`
Then in `template-studio-v2` run:
1. `npm install`
2. `npm link @accordproject/cicero-ui`
3. `npm run start`

Now making changes in `cicero-ui` and running `npm run transpile` in that repo will refresh your build.

**Comment by DianaLease** [comment]
> > > ooh, okay, I wanted to contribute to an issue opened by Diana concerning "Restyling the navigation size", please how do I get to preview changes I make to Cicero Ui components, like the Navigation component? should I just import the components in the file being displayed in the demo, so I can preview then remove the import when I'm done?
> > 
> > 
> > That's a really good question. I think we've been using https://github.com/accordproject/template-studio-v2 to test those components in context. Maybe @irmerk or @DianaLease can confirm?
> 
> That is what we were doing. I think it would be good to get them in the cicero-ui demo though to test easily there. That would be a good thing to add and keep (as opposed to removing when you are done @jerrybuks)

You could just hard code some test data for the navigation component like we do with the content of the editor in the demo. I think that would be the easiest way to work on the styling.

**Comment by jerrybuks** [comment]
okay, it makes a lot more sense now. @irmerk don't you think this process of relying on the templating studio makes contributing a bit more difficult. Guess I will just do as @DianaLease said, so as to work on the styling when I'm done with that I will probably open a feature request to implement Diana's suggestion - "I think it would be good to get them in the cicero-ui demo though to test easily there".

**Comment by jerrybuks** [comment]
> Yes we are using `template-studio-v2` heavily as a development environment for `cicero-ui`. You should have two terminals open, one to your `cicero-ui` and one to `template-studio-v2`
> 
> In `cicero-ui` run:
> 
> 1. `npm install`
> 2. `npm run build`
> 3. `npm run transpile`
> 4. `npm link`
> 
> Then in `template-studio-v2` run:
> 
> 1. `npm install`
> 2. `npm link @accordproject/cicero-ui`
> 3. `npm run start`
> 
> Now making changes in `cicero-ui` and running `npm run transpile` in that repo will refresh your build.
> 
> This is described here: https://github.com/accordproject/cicero-ui#development

will be really cool to update this " https://github.com/accordproject/cicero-ui#development", as explicitly as you did her, cause this isn't so clear as it doesn't mention the need for the "template-studio-v2"

**Comment by jeromesimeon** [comment]
> okay, it makes a lot more sense now. @irmerk don't you think this process of relying on the templating studio makes contributing a bit more difficult. Guess I will just do as @DianaLease said, so as to work on the styling when I'm done with that I will probably open a feature request to implement Diana's suggestion - "I think it would be good to get them in the cicero-ui demo though to test easily there".

The demo in cicero UI and the demo in template studio v2 serve very different purposes. In Cicero UI you only test individual components. Template studio v2 has more of a real UI organization notably with a redux store which lets you test interaction between those components.

**Comment by jerrybuks** [comment]
okay, thanks for the clarification.
> > okay, it makes a lot more sense now. @irmerk don't you think this process of relying on the templating studio makes contributing a bit more difficult. Guess I will just do as @DianaLease said, so as to work on the styling when I'm done with that I will probably open a feature request to implement Diana's suggestion - "I think it would be good to get them in the cicero-ui demo though to test easily there".
> 
> The demo in cicero UI and the demo in template studio v2 serve very different purposes. In Cicero UI you only test individual components. Template studio v2 has more of a real UI organization notably with a redux store which lets you test interaction between those components.
