### ISSUE TITLE
Component: README.md Editor

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero-ui#3]
- Based on `markdown-editor`

**Comment by ankingcodes** [comment]
@irmerk @jeromesimeon I'd like to work on this. 
Need some more details on the issue.

**Comment by irmerk** [comment]
@ankingcodes I think this issue is a bit stale, we need to revisit it, but I don't think we are going to keep pursuing the Editor components from ~April 2019.

**Comment by irmerk** [comment]
@jeromesimeon any thoughts about #2, #3, #4, #5, and #7, being stale?

**Comment by jeromesimeon** [comment]
Stale!
