### ISSUE TITLE
Toggle lockText button UI improvements

### ISSUE THREAD

**Issue by elit-altum** [accordproject/cicero-ui#301]
**Is your feature request related to a problem? Please describe.**
The toggle text button is central to the functionality and could use some UI improvements. Including it's margin, color etc.

**Describe the solution you'd like**
If approved, I'd like to work on modifying it's appearance and position by getting inputs from someone from the community and then discussing possible UI enhancements. 

**Additional context**
A screenshot of the current look is provided:
![image](https://user-images.githubusercontent.com/41413622/75364375-a9549500-58e1-11ea-9ed1-8354ec90dc06.png)

**Comment by elit-altum** [comment]
@irmerk If you approve this, I intend to use the local styling if only the button has to be customised, or I can create a site theme as recommended on http://learnsemantic.com/developing/customizing.html#customizing-ui-elements for any more elements that may need improvements.

**Comment by irmerk** [comment]
I believe this is leftover that no one has gotten around to removing. We either don't need this anymore, or there is still the issue of toggling a `lockText` property and having it take effect in the Slate editor. @dselman @DianaLease is this stale or still an issue?

**Comment by DianaLease** [comment]
The button is just there to test the `lockText` functionality, which is working. I don't think it is necessary to style it. It's good to keep in the demo to test new features easily in both states of lockText true and false.

**Comment by elit-altum** [comment]
Thank you for your review @DianaLease and @irmerk.
I thought it would be an improvement of the general UI by implementing this. I also wanted to add some info text which would indicate clearly that the slate text maybe edited or not along with a lock/unlock toggler icon.

If this is not required, should I proceed to close the issue?
Thank you.

**Comment by irmerk** [comment]
I think because this is in the demo, it's not a priority - there are a lot of other issues that could be more useful to focus on.
