### ISSUE TITLE
Variable Background Colors

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#314]
**Is your feature request related to a problem? Please describe.**
Variables should have customizable background colors, as well as only having colors in `lockText` mode.

**Describe the solution you'd like**
Allow for props to dictate the color of the variables, and only display this when `lockText` is true.

**Describe alternatives you've considered**
Open to input.

**Additional context**
Referenced in accordproject/markdown-editor#124

**Comment by elit-altum** [comment]
@irmerk  Could you tell me if there is any prop which can be accessed by the ```.variable``` class to indicate if the ```lockText``` is true or false ?

**Comment by irmerk** [comment]
Not sure I understand the question completely, but you could find `lockText` in [this function](https://github.com/accordproject/cicero-ui/blob/master/src/plugins/VariablePlugin.js#L93-L109), probably off the `editor`.

**Comment by elit-altum** [comment]
> 
> 
> Not sure I understand the question completely, but you could find `lockText` in [this function](https://github.com/accordproject/cicero-ui/blob/master/src/plugins/VariablePlugin.js#L93-L109), probably off the `editor`.

It's not there. It returns ```undefined```

**Comment by elit-altum** [comment]
@irmerk I have made the ```backgroundColor``` property responsive to ```editor.props.lockText```. It looks something like this :

![image](https://user-images.githubusercontent.com/41413622/75612562-a8726c00-5b4a-11ea-82b3-5815a98ae731.png)


Contrast of yellow : blue is 9.55

**Comment by irmerk** [comment]
Yes that works, we can provide more feedback then!

**Comment by elit-altum** [comment]
> 
> 
> Yes that works, we can provide more feedback then!

@irmerk Please review!
https://github.com/accordproject/cicero-ui/pull/316

**Comment by a4aditya** [comment]
This Issue should be Closed 👍

**Comment by irmerk** [comment]
Once #316 is merged this will be closed.
