### ISSUE TITLE
Make Clause Template background color lighter

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/cicero-ui#322]
Change clause template background color from #ECF0FA to #F9FBFF to increase contrast. Increased contrast will improve accessibility and allow more flexibility for how we design future improvements like this: https://github.com/accordproject/cicero-ui/issues/314

Current
![image](https://user-images.githubusercontent.com/40569793/75925552-de5b6d00-5e36-11ea-960b-2fdbfdc2c269.png)

Proposed
![image](https://user-images.githubusercontent.com/40569793/75925505-d1d71480-5e36-11ea-99ed-f005b8f9e7fb.png)

**Comment by shrey-sachdeva2000** [comment]
Can I work on this one? @Michael-Grover

**Comment by Michael-Grover** [comment]
Sure

**Comment by elit-altum** [comment]
@shrey-sachdeva2000 @irmerk This is actually a continuation of my PR here at https://github.com/accordproject/cicero-ui/pull/318#issuecomment-594607135 so I had already made the changes along with the colors and margins. Should I continue now ?

**Comment by shrey-sachdeva2000** [comment]
> @shrey-sachdeva2000 @irmerk This is actually a continuation of my PR here at [#318 (comment)](https://github.com/accordproject/cicero-ui/pull/318#issuecomment-594607135) so I had already made the changes along with the colors and margins. Could I please continue with it and make a PR ?
> 
> Thank you!

I didn't mean to step on any toes @elit-altum. Was just making the PR when you commented. I don't mind taking it back if you'd like!

**Comment by elit-altum** [comment]
> > @shrey-sachdeva2000 @irmerk This is actually a continuation of my PR here at [#318 (comment)](https://github.com/accordproject/cicero-ui/pull/318#issuecomment-594607135) so I had already made the changes along with the colors and margins. Could I please continue with it and make a PR ?
> > Thank you!
> 
> I didn't mean to step on any toes @elit-altum. Was just making the PR when you commented. I don't mind taking it back if you'd like!

I don't know now. I guess some formatting changes were also to be made which were discussed in the previous PR. I think we should let @irmerk and @Michael-Grover decide

**Comment by elit-altum** [comment]
@shrey-sachdeva2000 I will move on to handle the spacing and margins instead.

**Comment by irmerk** [comment]
@elit-altum sorry! I didn't fully read through the issue again before merging #323

**Comment by elit-altum** [comment]
No problem @irmerk!
I'll make a separate PR for spacing and borders as suggested by @Michael-Grover

**Comment by irmerk** [comment]
Whoopsie, reopening because the Clause Header that shows on hover needs it's gradient color updated to be in line with this new background color.

**Comment by elit-altum** [comment]
@irmerk Can I handle this?
