### ISSUE TITLE
Broken Links in Readme.md  

### ISSUE THREAD

**Issue by a4aditya** [accordproject/cicero-ui#328]
**Describe the bug**
The Link for the highlighted text on the screenshot is broken. The two of the component don't have a repository also. 
Link to the Readme File: https://github.com/accordproject/cicero-ui/blob/master/README.md
![#3](https://user-images.githubusercontent.com/39999719/76146962-e11bc380-60bd-11ea-8d77-ff5aa73926f9.PNG)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Readme.md'
2. Scroll down to 'Implementation'
3. See error

**Expected behaviour**
The link should provide a link to the Readme.md file for every component

**Comment by sanyamdogra** [comment]
Hi @a4aditya, The components you mentioned are under the heading "Still in development". I guess once they will be developed, these links will have their meaning.

**Comment by irmerk** [comment]
Yes they probably should not have been linked in the first place, but they are not at their first stage yet. You could remove the links or close this issue.

**Comment by sanyamdogra** [comment]
I guess it's a minor fix, should I make a PR with removing the link? @irmerk

**Comment by irmerk** [comment]
Sure thing
