### ISSUE TITLE
Conditional Variable is Editable

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#339]
**Describe the bug**
Conditional variables are editable

**To Reproduce**
1. Go to [the demo](https://cicero-ui.netlify.com/)
2. Click on before the conditional variable
3. Right arrow into the conditional variable
4. Type

**Expected behavior**
This should be protected and not allowed

**Comment by jerrybuks** [comment]
Let me fix this.

**Comment by jerrybuks** [comment]
should

> **Describe the bug**
> Conditional variables are editable
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to [the demo](https://cicero-ui.netlify.com/)
> 2. Click on before the conditional variable
> 3. Right arrow into the conditional variable
> 4. Type
> 
> **Expected behavior**
> This should be protected and not allowed

should this be protected, only when lockTestState is true or should it  be protected whether or not lockTestState is true/false?

**Comment by irmerk** [comment]
I believe we have `isEditable` functions that check to make sure a user can type already. So a conditional variable should be treated the same as non-variable text in that a user should not be able to edit it. And yes I think this all pertains to `lockText` being true.

**Comment by jerrybuks** [comment]
> I believe we have `isEditable` functions that check to make sure a user can type already. So a conditional variable should be treated the same as non-variable text in that a user should not be able to edit it. And yes I think this all pertains to `lockText` being true.

yeah, on it
