### ISSUE TITLE
Test ContractEditor functionality

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#34]
# Related Issues
- Issue #1 
- Issue [#23](https://github.com/accordproject/template-studio-v2/issues/23) in TSv2
- Issue #33 

## Tasks:
- Contingent upon Issue #33, implement tests for this component.

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can possibly provide for multiple pull requests.

**Comment by Innovator007** [comment]
Can i work on this issue?

**Comment by mttrbrts** [comment]
@irmerk any further guidance for @Innovator007 ?

**Comment by Innovator007** [comment]
yeah tell me so i can work on it asap :)

**Comment by irmerk** [comment]
Sure thing. The `ContractEditor` is using `markdown-editor`, which is built on [SlateJS](https://docs.slatejs.org/). We want to build a robust set of unit tests to ensure a number of user actions are tested, and this will give us a better idea of what changes we make will do to the functionality of the editor.

So this issue can have multiple PRs. Some ideas off the top of my head:

- Add a mocked clause template
- Add a paragraph and change it to different heading styles
- Add a paragraph and alter the formatting of a section
  - Bold
  - Italic
  - Code block
  - Hyperlink
- Add a paragraph and alter the whole block into a quote

Because this is in `cicero-ui`, we want to test this being able to handle clause templates, so testing `lockText` and editing variables can be in there too.

**Comment by Innovator007** [comment]
Hi @irmerk so do i have to write the test for each of the above test cases?

**Comment by irmerk** [comment]
@Innovator007 You specifically don't have to, but that is what this issue is tracking: unit testing this component (`ContractEditor`) for as many scenarios as possible.

**Comment by Innovator007** [comment]
Okay cool, i will give this a shot.

**Comment by sahalsaad** [comment]
HI @Innovator007, since there is 4 points suggested. Can we split?

>This issue can possibly provide for multiple pull requests.

**Comment by Innovator007** [comment]
Hi @sahalsaad yeah sure we can split it i have started to approach first so i think you can proceed with 3rd and fourth :)

**Comment by sahalsaad** [comment]
@Innovator007 . Sure . Thanks

**Comment by Innovator007** [comment]
Welcome @sahalsaad :)

**Comment by sahalsaad** [comment]
Hi @irmerk . I look into this. But not sure how to write the above use case in unit test. Seems like more to e2e test. 

The only unit test I can see is to test the `value` or `onChange` logic.

**Comment by irmerk** [comment]
We'll want to do as many unit tests as possible, and if e2e is a better route then we should probably pursue that.

**Comment by sahalsaad** [comment]
Currently there is no e2e setup yet for this project. Maybe can have a ticket for setup the e2e?
I will add unit test based on what I mention above.

**Comment by Innovator007** [comment]
Hi @irmerk can you explain to me how to add a mocked clause template to test since i am a little bit confused.

**Comment by Innovator007** [comment]
Hi @irmerk i am a bit confused on how to approach this thing can you suggest me some route to follow?

**Comment by irmerk** [comment]
@Innovator007 sure, I was thinking of taking the approach from [the demo code](https://github.com/accordproject/cicero-ui/blob/master/demo/src/index.js) and using that as a basis to initialize unit tests and check for attributes, making sure `lockText` was on or off, that you can add characters outside a clause when it is on, etc.

**Comment by Innovator007** [comment]
Hi @irmerk ,sorry but i am unassigning myself since couldn't find a way to implement this, i think @sahalsaad can do a better job at testing stuff :)

**Comment by irmerk** [comment]
#197 makes a good impact on this issue. Closing for now.

**Comment by irmerk** [comment]
@sahalsaad there is [an error](https://travis-ci.org/accordproject/cicero-ui/builds/605527291#L682) with one of the tests:

```
<ContractEditor /> › on initialization › should render specified value

    Found multiple elements with the role "textbox"

    (If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).
```

**Comment by sahalsaad** [comment]
Hi @irmerk . I can't replicate that issue. I saw the latest build also successful. Is there any special steps to replicate that issue ?

**Comment by irmerk** [comment]
I commented out the test in #207, so it should be just uncommenting it and running the test.

**Comment by irmerk** [comment]
Relates to #336

**Comment by irmerk** [comment]
Closing for https://github.com/accordproject/web-components/issues/15
