### ISSUE TITLE
Delete Icon is not functional currently.

### ISSUE THREAD

**Issue by SaiAshish9** [accordproject/cicero-ui#351]
![image](https://user-images.githubusercontent.com/43849911/76875763-01eed080-6897-11ea-8a26-68c7bfc4621a.png)

**Comment by SaiAshish9** [comment]
I'm currently working on this issue.

**Comment by irmerk** [comment]
This isn't an issue, none of those buttons have functionality. They are passed functionality from whoever uses this component in the app that consumes `cicero-ui`. The demo has no functionality because we don't pass a function to it.

**Comment by SaiAshish9** [comment]
Oh thank you Joelene !
