### ISSUE TITLE
[FEATURE] Add a shortcut list modal 

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-ui#354]
**Is your feature request related to a problem? Please describe.**
Currently, there is no modal which could show a list of shortcuts. This could be helpful for people to view them in one place rather than hover on each one of them.

**Describe the solution you'd like**
Create a button which could trigger a modal, displaying a list of shortcuts in the demo.

**Additional context**
I would like to implement it.

**Comment by irmerk** [comment]
@Michael-Grover any thoughts on this?

**Comment by Michael-Grover** [comment]
@nik72619c can you show examples of other products that do something like this?

**Comment by Michael-Grover** [comment]
I'm not sure if this is necessary. There's already a list of shortcuts in the documentation

**Comment by nik72619c** [comment]
I saw something in the following project, and thats why this struck my mind :-
https://vega.github.io/editor/#/

The shortcut list can be found under the help modal.

**Comment by Michael-Grover** [comment]
this product has way more shortcuts than we have, and our shortcuts are mostly standard ones like cmd+b or cmd+k. I don't think a shortcut list within the UI is necessary for the number of shortcuts we have.
