### ISSUE TITLE
Add Class prop

### ISSUE THREAD

**Issue by shakti97** [accordproject/cicero-ui#355]
**Is your feature request related to a problem? Please describe.**
I am currently using the word add in, when I hover over the button, it changes its background to white and there is no prop to handle hover

**Describe the solution you'd like**
instead of three different prop( Action button, Action Button Bg, Action Button Border) on any item i.e. Action we can just use a prop class which will cater all the things.

**Additional context**
I would like to work on this behaviour

**Comment by irmerk** [comment]
I believe [this issue](https://github.com/accordproject/cicero-ui/issues/320) is tracking a solution to this problem. Does that sound accurate?

**Comment by shakti97** [comment]
yes, closing this issue
