### ISSUE TITLE
If searched template is not found, it should return no result found message

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-ui#359]
**Describe the bug**
On searching something that is not present in the template list, there should be a message saying that the records were not found but nothing is seen there.

**To Reproduce**
1. Go to `Template Library List`
2. Search something which is not present in the list

**Expected behavior**
A message should be provided indicating that `no results were found`

**Screenshots**
<img width="329" alt="Screenshot 2020-03-29 at 8 02 48 PM" src="https://user-images.githubusercontent.com/30630904/77851735-4d3ea280-71f8-11ea-9b44-ec166c1a8de7.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 10.15.0

**Additional context**
I would like to work on this

**Comment by irmerk** [comment]
@Michael-Grover thoughts/ideas? This is for the `TemplateLibrary` in `cicero-ui`

**Comment by Michael-Grover** [comment]
this sounds good to me

**Comment by irmerk** [comment]
@nik72619c is there any update on this?

**Comment by nik72619c** [comment]
@irmerk would be filing another PR for this
