### ISSUE TITLE
extra clickable area of import buttons

### ISSUE THREAD

**Issue by nik72619c** [accordproject/cicero-ui#365]
**Describe the bug**
The buttons like `import from vs code` and `upload CTA file` have an extended clickable area. Therefore, the buttons are clickable beyond their content.

**To Reproduce**
1. Open the `template library` section of cicero-ui
2. hover on the `import from vs code` button beyond its content
3. Notice the extra spacing

**Expected behavior**
The user should be able to click only on the content of the text and not beyond it

**Screenshots**
![WhatsApp Image 2020-04-04 at 11 47 35 PM](https://user-images.githubusercontent.com/30630904/78458420-cfced280-76ce-11ea-8fae-ed6023fd23c7.jpeg)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina v10.12.0
 - Browser chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by nik72619c** [comment]
@irmerk @DianaLease,discussed this issue already on slack, filing a PR for it.

**Comment by irmerk** [comment]
@nik72619c could you copy over the conversation or a summary of it?
