### ISSUE TITLE
Pressing backspace with caret at start of variable allows delete of non variable text

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#374]
Pressing the backspace key with caret at start of variable allows delete of non variable text.

**To Reproduce**
1. https://cicero-ui.netlify.com
2. Place caret at the end of "Party A"
3. Press backspace to delete all text in the variable except the "
4. Press left arrow key
5. Press backspace
6. The line break outside the variable is removed

**Expected behavior**
Should not be able to delete text outside of variables.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari

**Comment by irmerk** [comment]
This looks solved, but a similar issue: 

1. https://cicero-ui.netlify.com
2. Place cursor at beggining of "Party A"
3. Press <kbd>DELETE</kbd> to delete all text in the variable
4. Press once more
5. Space between variable and next word is removed and cannot be readded

**Comment by jeromesimeon** [comment]
> This looks solved, but a similar issue:
> 
> 1. https://cicero-ui.netlify.com
> 2. Place cursor at end of "Party A"
> 3. Press DELETE once
> 4. Space between variable and next word is removed and cannot be re-added

I'm not sure we are robust when we delete the `"` at the end (if this is what happens in this example). Could you add the Slate DOM before and after edit in that scenario?
