### ISSUE TITLE
No css for block quote

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#375]
**Describe the bug**
Formatting some text as a block quote indents the text, but no additional css is applied.

**To Reproduce**
1. Select text
2. Press the block quote toolbar button
3. Text gets indented

**Expected behavior**
Some formatting is applied - e.g. see what Medium or what other markdown editors use.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version Latest

**Comment by arteevraina** [comment]
@dselman Can I work on this?

**Comment by irmerk** [comment]
@arteevraina sure thing, look for input from @Michael-Grover on this as well.

**Comment by arteevraina** [comment]
@irmerk Sure!

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/79132599-a1a95c80-7d78-11ea-8df6-9b4aabca4f5b.png)

I think block quotes in Cicero UI should have a horizontal line in addition to the existing indentation like markdown editor already has:

![image](https://user-images.githubusercontent.com/40569793/79132638-b259d280-7d78-11ea-841f-8a0942953a55.png)

**Comment by arteevraina** [comment]
@irmerk This can be closed now.
