### ISSUE TITLE
Storybook packaged as a dependency

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#376]
https://github.com/accordproject/cicero-ui/blob/master/package.json#L28

Should story book be a dependency? How does this impact bundle size?

**Comment by arteevraina** [comment]
@dselman I would like to work on this.

**Comment by irmerk** [comment]
This ties in with #358 and #315, @98lenvi is working on it.

**Comment by DianaLease** [comment]
@98lenvi I would check out the install docs here: https://storybook.js.org/docs/guides/guide-react/#step-1-add-dependencies
