### ISSUE TITLE
Undoing Breaks The Editor 

### ISSUE THREAD

**Issue by jerrybuks** [accordproject/cicero-ui#378]
**Describe the bug**
undoing multiple times breaks the editor.

**To Reproduce**
1. Go to [the demo](https://cicero-ui.netlify.com/)
2. Click on anywhere inside "Party A''
3. move your cursor to right using the right arrow key, to just immediately after the last " of "Party A"
4. press backspace till you reach the first "
5. Hold ctrl+z or keep clicking undo, the editor breaks immediately it undoes up till the initial state
**Expected behavior**
Undoing should not break the application, but stop once it reaches the expected state

**Desktop **
 - OS: (Linux)
 - Browser (chrome)

**Comment by irmerk** [comment]
Calling this line in `withLinks` is erroring because there is no parent:

```js
isSelectionLink = editor => Node.parent(editor, editor.selection.focus.path).type === 'link';
```

This is stemming from `onChange`:

```js
if (selection && isSelectionLinkBody(editor)) { setShowLinkModal(true); }
```

**Comment by irmerk** [comment]
There seems to be a need to check in `onChange` to see if the editor is in focus? Trying to put `try/catch` in `isSelectionLink` kicks the issue down the road to the next function that's called and has the same issue.
