### ISSUE TITLE
Can apply bold and italics to inline code

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#385]
**Describe the bug**
You can use the toolbar to add both bold and italics to inline code. I don't think this is valid markdown and won't roundrip through the markdown transform.

**To Reproduce**
1. Go to https://cicero-ui.netlify.com
2. Click "code"
3. Press the bold and italic button
4. See code, italic and bold are all applied to the text (see screenshot).

**Expected behavior**
You should not be able to apply formatting to code.

**Screenshots**

![Screenshot 2020-04-14 at 19 01 23](https://user-images.githubusercontent.com/623108/79258019-6abf6d80-7e82-11ea-91f8-5676b0be8902.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari
 - Version 13.1

**Comment by dselman** [comment]
I take it back... I DOES appear to be valid commonmark. Just verified with the Dingus:

## Try CommonMark

You can try CommonMark here.  This dingus is **`powered`** by
[commonmark.js](https://github.com/jgm/commonmark.js), the
JavaScript reference implementation.

**Comment by jeromesimeon** [comment]
Sure is 😉

**Comment by jeromesimeon** [comment]
Even:

<img width="757" alt="Screenshot 2020-04-14 at 2 08 23 PM" src="https://user-images.githubusercontent.com/670099/79258625-6d599d00-7e59-11ea-872d-9b0829c1116b.png">
