### ISSUE TITLE
Enhance Storybook

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#386]
Our Storybook demo needs upgrading to easily develop and locally test all the components and their functionality.

Recommended to look into and utilize:
- [Storybook](https://storybook.js.org/)
- Issue #315

Some initial goal ideas:
- [x] [Publish our Storybook to Netlify](https://cicero-ui.netlify.app/)
- [ ] Remove `Demo` story (or propose new structure to Storybook?)
- [ ] Remove props knobs (#320)
- [ ] `ContractEditor` variants
  - [ ] Huge document
  - [ ] ???
- [ ] `TemplateLibrary` variants
  - [ ] Create empty template?
  - [ ] ???
- [ ] ???

**Comment by dselman** [comment]
I am working on this.
