### ISSUE TITLE
Undoing After deleting values before "." breaks the editor

### ISSUE THREAD

**Issue by jerrybuks** [accordproject/cicero-ui#393]
**Describe the bug**
After deleting numbers before a decimal point, undoing to a certain point breaks the editor.

1. Go to the [demo](https://cicero-ui.netlify.app/) 
2. In the demo section, scroll down to the bottom where you have the bulleted list
3. place you cursor at the end of the line of any of the list items (i.e after the percentage sign)
4. move your cursor left to just before the first decimal point '.'
5. hit backspace about two times and undo about three times, the editor breaks.

**Expected behavior**
The editor should not break

**Screenshots**
https://www.loom.com/share/e329553e4fec4b2fbc89f6e2cffb1ddd

**Desktop (please complete the following information):**
 - OS: [Linux
 - Browser: Chrome

**Comment by irmerk** [comment]
This may be the same issue in https://github.com/accordproject/cicero-ui/issues/378, keeping open for now.

**Comment by jerrybuks** [comment]
> This may be the same issue in #378, keeping open for now.

I think they looked similar, but noticed the PR you linked in #378 stopped the editor from breaking, but this issue still persisted

**Comment by irmerk** [comment]
@jerrybuks I don't see t he issue persisting in [this build](https://deploy-preview-394--cicero-ui.netlify.app/?path=/story/components-demo--demo).

**Comment by jerrybuks** [comment]
> @jerrybuks I don't see t he issue persisting in [this build](https://deploy-preview-394--cicero-ui.netlify.app/?path=/story/components-demo--demo).

yeah, its fixed!
