### ISSUE TITLE
Table Accessibility

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#54]
# WCAG 2.0 Level A [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) (Info and Relationships)

## Tasks
- Ensure `table` elements are accessible through proper usage of:
  -  `<thead>` and `<tbody>` for better navigation through a table
  - Column and Row header `<th>` elements need a scope attribute 
      - (`<th scope="col">` and `<th scope="row">`)
  - Tables should contain a `<caption>` (for the title) to help describe the `table`
      - Switch the header used prior to the `table` element with a caption element *inside* the `table`
      - Add a visually hidden description to the `<caption>`

## Related Issues: 
- Issue [#39](https://github.com/accordproject/template-studio-v2/issues/39) in Template Studio v2

**Comment by MKrupauskas** [comment]
This should probably also be closed as the [related issue in Template Studio v2](https://github.com/accordproject/template-studio-v2/issues/39) was closed. There aren't any tables in this project either :)
