### ISSUE TITLE
Rendering issue filtering templates 

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#75]
Filtering of templates in the template library component introduces spaces between each card used for the templates.

**To Reproduce**
1. Start typing "acceptance" into the filter box

**Expected behavior**
Templates are filtered and laid out correctly.

**Screenshots**
<img width="381" alt="Screenshot 2019-07-03 at 15 10 44" src="https://user-images.githubusercontent.com/623108/60598537-c3ff5a00-9da4-11e9-86be-d9f8b76a2ddd.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Both Chrome and Safari
 - Version: Latest

**Comment by irmerk** [comment]
Resolved with #72
