### ISSUE TITLE
Support editable variables

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero-ui#76]
We need to support a variable serialisation that allows us to lock the documents against edits, except for variable sections.

When a variable is being edited we need to be able to relate the Slate block to the contract model property, so we know the type and how the contract instance (JSON) should be updated.

I think variables in Slate should be represented as "marks" because they apply to a range of the document and must have their positions updated as the document is edited.

Proposal below.

====

```
## Testing

You can declare a variable in a template using [{name}].

Or we could use <variable id="name"/> to declare a variable, 
which is more common mark parser friendly.

This is an inline variable 
<variable id="name" value="with a value"/> too.

This is a variable with complex content.

``` <variable id="name">
this is a

multi-line value.
</variable>
```

The `variable` tag will be handled by a `Variable` plugin into the markdown editor. The plugin will create text blocks with the variable mark set and metadata on the mark that indicates the FQN of the model element for the variable.

Clicking on a variable should open a type-specific editor (such as a calendar editor for a DataTime variable).

**Comment by jeromesimeon** [comment]
Here is the current markup generated by the `dynamic-template` branch of Ergo:

```
bash-3.2$ cat examples/interestsvar/logic2.tem 
This is a fixed interest loan to the amount of [{loanAmount}]
at the yearly interest rate of [{rate}]%
with a loan term of [{loanDuration}],
and monthly payments of {{monthlyPaymentFormula(contract.loanAmount,contract.rate,contract.loanDuration)}}
bash-3.2$ ./packages/ergo-cli/bin/ergorun.js generateText examples/interestsvar/model.cto examples/interestsvar/interests.ergo examples/interestsvar/logic2.ergo --template examples/interestsvar/logic2.tem --contract examples/interestsvar/contract.json --markdown 
12:28:29 - info: This is a fixed interest loan to the amount of <variable name="loanAmount" value="100000.0"/>
at the yearly interest rate of <variable name="rate" value="2.5"/>%
with a loan term of <variable name="loanDuration" value="15"/>,
and monthly payments of <computed value="667.0"/>

```

**Comment by irmerk** [comment]
@DianaLease is this essentially finished with work like #223?

**Comment by DianaLease** [comment]
@irmerk Yes. I think the last part (`Clicking on a variable should open a type-specific editor (such as a calendar editor for a DataTime variable)`) should be made into a separate issue if it is not already.
