### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-ui#99]
I have yet to be able to fix these vulnerabilities. There may be a case for removing the `yarn.lock` file, as I'm unsure why it exists in the first place. As far as I know, `yarn` should not be used in this repo.

<img width="1003" alt="Screen Shot 2019-08-07 at 9 39 10 AM" src="https://user-images.githubusercontent.com/36460856/62627491-7c19a880-b8f7-11e9-8216-45dcdbe05608.png">

**Comment by Innovator007** [comment]
Hi @irmerk i researched about yarn.lock file and it says that it holds the version of the dependencies in it on yarn install and we should keep that in order to get the same output for every developer.

**Comment by mttrbrts** [comment]
Thanks @Innovator007 , you're correct. The real issue is that we should not have both `yarn.lock` and `package-lock.json`.

Most other AP repos use `npm` (which produces  `package-lock.json`) rather than `yarn` (which produces `yarn.lock` ).

**Comment by Innovator007** [comment]
Yes i agree with you @mttrbrts i can remove it and it won't affect anything but although we can run tests and confirm.

**Comment by Innovator007** [comment]
Can i work on this?

**Comment by Innovator007** [comment]
Hi @irmerk i have made a pull request [here](https://github.com/accordproject/cicero-ui/pull/171), have tested and everything works fine, can you review it. Thanks :)
